# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nlines_ <- function(filename, with_eof) {
    .Call('_fpeek_nlines_', PACKAGE = 'fpeek', filename, with_eof)
}

head_str_ <- function(filename, n) {
    .Call('_fpeek_head_str_', PACKAGE = 'fpeek', filename, n)
}

head_print_ <- function(filename, n) {
    invisible(.Call('_fpeek_head_print_', PACKAGE = 'fpeek', filename, n))
}

tail_str_ <- function(filename, n) {
    .Call('_fpeek_tail_str_', PACKAGE = 'fpeek', filename, n)
}

tail_print_ <- function(filename, n) {
    invisible(.Call('_fpeek_tail_print_', PACKAGE = 'fpeek', filename, n))
}

file_iconv_ <- function(filename, encoding, encto) {
    invisible(.Call('_fpeek_file_iconv_', PACKAGE = 'fpeek', filename, encoding, encto))
}

