# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

file_nlines_ <- function(filename) {
    .Call('_fpeek_file_nlines_', PACKAGE = 'fpeek', filename)
}

file_head_str_ <- function(filename, n) {
    .Call('_fpeek_file_head_str_', PACKAGE = 'fpeek', filename, n)
}

file_head_print_ <- function(filename, n) {
    invisible(.Call('_fpeek_file_head_print_', PACKAGE = 'fpeek', filename, n))
}

file_tail_str_ <- function(filename, n) {
    .Call('_fpeek_file_tail_str_', PACKAGE = 'fpeek', filename, n)
}

file_tail_print_ <- function(filename, n) {
    invisible(.Call('_fpeek_file_tail_print_', PACKAGE = 'fpeek', filename, n))
}

file_iconv_ <- function(filename, encoding, encto) {
    invisible(.Call('_fpeek_file_iconv_', PACKAGE = 'fpeek', filename, encoding, encto))
}

